### ISSUE TITLE
bad file descriptor

### ISSUE THREAD

**Issue by prankshtain** [AvisEngine/AVIS-Engine-Python-API#2]
I  use ubuntu 22.04 and 3.10.6 python version , when I run the Example.py I see this error showing up in terminal,I also reset and start the server again but nothing had changed 

Error:
  File "/fira2023_sim/FiraAuto.py", line 123, in __del__
  File "/fira2023_sim/FiraAuto.py", line 116, in stop
  File "/fira2023_sim/FiraAuto.py", line 57, in setSpeed
OSError: [Errno 9] Bad file descriptor

**Comment by prankshtain** [comment]
![image](https://user-images.githubusercontent.com/74510848/229363936-e468b9de-1e9e-4d6d-91ba-f0934a25f64e.png)
I have problem with recv method

**Comment by AmirmohammadZarif** [comment]
The problem seems to be related to the version of the API (Regarding the log), the API version 2.0.1 won't work with version 1.0.0 simulators and makes them deprecated.
