### ISSUE TITLE
Higher image quality

### ISSUE THREAD

**Issue by AliDjango** [AVISEngine/AVIS-Engine-Python-API#6]
Hello
Is there a way to have higher resolution camera when using with Avis Engine 1.2.0?
256x256 is a really low resolution and prevents us from from detecting lanes & signs with high precision.

**Comment by AmirmohammadZarif** [comment]
Hello, 

Commit: daac8ed075269e192fe319f79d0a5501dde005b3
AVIS Engine version 1.2.4 has already been released in which you can achieve higher resolutions.

**Comment by AmirmohammadZarif** [comment]
daac8ed075269e192fe319f79d0a5501dde005b3
